server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html index.csr.html index.htm;

    # Supporto per il routing HTML5 / Single Page Application (SPA) di Angular
    location / {
        try_files $uri $uri/ /index.csr.html /index.html;
    }

    # Proxy opzionale verso il backend per evitare problemi di CORS in produzione se serviti sullo stesso dominio
    location /api/ {
        proxy_pass http://goodexchange_backend:3000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Configurazione di caching per file statici (CSS, JS, Immagini)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
